apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
      livenessProbe:
        httpGet:
          port: 80
          path: /index.html
      readinessProbe:
        httpGet:
          port: 80
          path: /index.html
      volumeMounts:
        - name: app-config-volume
          mountPath: /tmp/
  volumes:
    - name: app-config-volume
      configMap:
        name: app-config