apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "delete", "update", "watch", "create"]
  - apiGroups: [""]
    resources: ["ConfigMap"]
    verbs:
      - "list"