apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-rolebinding
subjects:
  - apiGroup: rbac.authorization.k8s.io
    name: dev-user
    kind: User
roleref:
  apiGroup: rbac.authorization.k8s.io
  name: my-role
  kind: Role