apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-rq
  namespace: dev
spec:
  hard:
    pods: "10"
    limits.cpu: 500m
    limits.memory: 512Mi
    requests.cpu: 250m
    requests.memory: 256Mi