apiVersion: v1
kind: ReplicaController
metadata:
  name: nginx-rc
  labels:
    app: nginx
    env: test
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        env: test
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 2
