apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              port: 80
              path: /index.html
          readinessProbe:
            httpGet:
              port: 80
              path: /index.html
      imagePullSecrets:
        - name: regcred
  replicas: 2
  selector:
    matchLabels:
      app: nginx