apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/25 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ubuntu
              image: ubuntu
              command: ['expr', '3', '+', '5']
          restartPolicy: Never
