apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /opt
          name: my-pvc-vol
  volumes:
    - name: my-pvc-vol
      persistentVolumeClaim:
        claimName: my-pvc