apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-rolebinding
subjects:
  - name: my-sa
    kind: ServiceAccount
    namespace: default
roleRef:
    name: my-role
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io