apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
          volumeMounts:
            - mountPath: /opt
              name: data-vol
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx-headless
  volumeClaimTemplates:
    - metadata:
        name: data-vol
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: google-storage
        resources:
          requests:
            storage: 500Mi